config/routes.rb
Rails.application.routes.draw do

  

  get 'records/new'

  devise_for :users, :controllers => { registrations: 'registrations', 
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'tags/:tag', to: 'items#index', as: :tag

  root 'static_pages#home'
  get 'static_pages/about', as: :about
  post 'global_search' => 'static_pages#global_search_results', as: 'global_search'
  post 'return_item/:item_id' => 'items#return_item', as: 'return_item'
  get 'lend_item/:item_id' => 'items#lend_item', as: 'lend_item'

  resources :locations do 
    get 'search'  =>  'items#search_submit', as: 'item_search'
    resources :items do
      resources :records, only: [:new, :create, :index]
    end 
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  include PgSearch

  belongs_to :location
  belongs_to :user
  has_many :records, dependent: :destroy
  accepts_nested_attributes_for :records

  
  has_attached_file :avatar, :styles => { :medium => "250x250!>", :thumb => "100x100>" }, :default_url => "Logo.png"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :name, :description, presence: true
  validates :name, length: { maximum: 24 }

	acts_as_taggable # Alias for acts_as_taggable_on :tags
  # acts_as_taggable_on :skills, :interests

  pg_search_scope :search_items, against: [:name]
                  # :if => :search_valid?
                  # :if => lambda { |item| item.user_id = current_user.id  }

  paginates_per 60

  # def item_search(search_input)
  #   Item.search(search_input)
  # end 

  # def search_valid?
  #   user_id == current_user.id
  # end





  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:index]
  before_action :set_location, except: [:return_item]
  before_action :set_item, only: [:show, :edit, :update, :destroy, :index]
  before_action :set_items, except: [:return_item]
  
  def index
    if params[:tag]
      @items = current_user.items.tagged_with(params[:tag])
      @items = @items.page(params[:page])
    end
      @items = @items.page(params[:page])
    @user = current_user
  end

  def show
    @record = @item.records.build

    if params[:btn] == "1"
      @edit = params[:btn]
      @lend = nil
    elsif params[:btn] == "lend"
      @lend = params[:btn]
      @edit = nil
    end


    respond_to do |format|
      format.html 
      format.js
      end
  end

  def new
    @item = @user.items.build
    @record = @item.records.build
    # @item.due_date = @item.records.last.date_due
  end

  def edit
    respond_to do |format|
      format.js 
    end

  end


  def create
      @item = @location.items.new(item_params)
      
      @item.user_id = @user.id
      

      if @item.save        
        if @item.is_borrowed && @item.due_date
          
          ReminderMailer.delay(run_at: @item.due_date - 2.days).reminder_email_user(@item)
          
        end
        # binding.pry
        respond_to do |format|
          format.html { redirect_to location_items_path(@location) }
          format.js
        end
        flash[:success] = "Item #{@item.name} added."
      else
        flash[:error] = "#{@item.errors.full_messages}"
        render 'new'
      end
    end

  def update
    if @item.update_attributes(item_params)

      redirect_to location_items_path(@location)
    else
      flash[:danger] = "Item creation failed"
       redirect_to location_items_path(@location)
    end
  end

  def destroy
    
    @item.destroy
    unless @item.is_borrowed
      flash[:notice] = "Item #{@item.name} deleted."
    else
      flash[:notice] = "Item #{@item.name} has been returned to #{@item.borrowed_from}"
    end
    redirect_to location_items_path(@location)
  end

  def search_submit
    @results = current_user.locations.find(params[:location_id]).items.search_items(params[:q]) 
    respond_to do |format|
      format.html {redirect_to location_items_path(@location), :result => @results}
      format.js
    end
  end

  def return_item
    @item = current_user.items.find(params[:item_id])
    @location = current_user.locations.find(@item.location_id)

    
    @item.update_attribute(:is_out, false)
    @item.records.last.update_attribute(:date_returned, Date.today)
    respond_to do |format|
      format.js { @record = @item.records.build 
                  
                }
    end
  end

  def show_records
    @item = Item.find(params[:item_id])
    @record = @item.records.build
    # @location = Location.find(@item.location_id)
    # binding.pry
  end
 
  private

    def set_user
      @user = current_user
    end

    def set_location
      @location = Location.find(params[:location_id])
    end

    def set_items
      @items =  @location.items.page(params[:page])
    end

    def set_item
      @item =  Item.find_by(id: params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :quantity, :price, :is_out, :due_date, :borrowed_from, :is_borrowed, :tag_list, :avatar, records_attributes: [:borrower_name, :date_due])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit.html.erb
<%= bootstrap_form_for [@location, @item] do |f| %>

    <%= f.file_field :avatar %>
    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.text_field :price %>
    <%= f.number_field :quantity %>

    <div class="form-group">
     <%= f.text_field :tag_list, class: "tagit ui-widget ui-widget-content ui-corner-all" %>
    </div>
    <%= f.submit %>
    <% if using_modal %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <% end %>
<% end %>

app/views/items/_is_out_form.html.erb
<%= bootstrap_form_for [@location, @item, @record] do |f| %>

	<%= f.text_field :borrower_name, class: 'form-control', label: "Borrower's Name", autofocus: true, placeholder: "Borrower's name" %>

	<%= f.text_field :borrower_email, class: 'form-control', label: "Borrower's Email(Optional)", placeholder: "Fill to send reminder email" %>

	<%= f.date_field :date_due, class: "date", label: "When do you want the item back by?", placeholder: "yyyy-mm-dd" %>


  <%= f.submit %>

<% end %>

app/views/items/_item.html.erb
<div class ="item-block user-item-block over-due-item-block checked-out-item search-block">

  <h4><%= item.name %></h4>
     
	<div class = "item-avatar img-center">
  	<%= link_to (image_tag item.avatar.url(:medium)), location_item_path(item.location_id, item.id), remote: true %>
  </div>

  <p>
    <span class="tags"> <%= raw item.tag_list.map { |t| link_to t, tag_path(t, item_id: item.id, location_id: item.location.id) }.join(', ') %>
    </span>
  </p>

  
  <div class = "location-info"> 
  	
      
      <%= link_to "Edit", location_item_path(item.location_id, item.id, btn: 1), method: "get", remote: true, class: "btn btn-primary btn-xs" %>

      <% if item.records.count > 0 %>
        <%= link_to "History", location_item_records_path(item.location_id, item), class: "btn btn-primary btn-xs" %>
      <% end %>

      <% if item.is_borrowed %>
        <%= link_to "Item returned to lender?", location_item_path(item.location_id, item), method: :delete, class: "btn btn-danger btn-xs" %>
      <% end %>
  
  </div>
    
</div>

app/views/items/_modal.html.erb
<div class="modal fade" id="newItem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Item</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/items/_new_form.html.erb
<div class="">
  <%= bootstrap_form_for [@location, @item], layout: :horizontal do |f| %>
    <%= f.file_field :avatar, label: "Upload image", label_class: "new-item-form" %>
    <%= f.text_field :name, label: "Name", label_class: "new-item-form", placeholder: "1-24 characters long" %>
    <%= f.text_area :description, label: "Description", label_class: "new-item-form" %>
    <%= f.text_field :price, label: "Price", label_class: "new-item-form" %>
    <%= f.number_field :quantity, label: "Quantity", label_class: "new-item-form" %>
    <%= f.text_field :tag_list, class: "tagit ui-widget ui-widget-content ui-corner-all", label: "Tags", label_class: "new-item-form" %>
    <%= f.check_box :is_borrowed, class: "checkbox", id: "item_is_borrowed", label: "Did you borrow this item?" %>
    <div class="record-form" style="<%= 'display: block;' if params[:item] && params[:item][:is_borrowed] == '1' %>">
      <%= f.text_field :borrowed_from, label: "From who?", label_class: "new-item-form" %> 
      <%= f.date_field :due_date, class: "date", label: "Due Date?", label_class: "new-item-form" %>
    </div>

    <%= f.submit 'Add Item', class: "btn btn-primary" %>
    <% if using_modal %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <% end %>
  <% end %>
</div>

app/views/items/_search_results.html.erb
<div class="container-fluid ">
  <div class ="row image-tiles" id="masonry_container">

		<% @results.each do |item| %>
 		<%= render partial: 'items/item', locals: {item: item} %>
 		<%end%>
	</div>
</div>

app/views/items/_show_item.html.erb
    <div class = "item-img">
      <%= image_tag @item.avatar.url(:medium) %>
    </div>
    <div class = "item-info">
      <div class = "center-box">
        
        <h4>
          Description: &nbsp;
          <span class = "item-value"> <%=@item.description %> </span>
        </h4>
        
        <h4>
          Price: &nbsp;
          <span class = "item-value"> <%=@item.price %> </span> 
        </h4>
        
        <h4>Quantity: &nbsp; 
          <span class = "item-value"> <%=@item.quantity %> </span> 
        </h4>        
        <p><%= @item.tag_list %></p>
      </div>

      <% if @edit.nil? && @lend.nil? %>
        <p class="text-center">
          <% unless @item.is_borrowed %>
            <%= link_to " Delete", location_item_path(@location, @item), method: :delete, class: "fa fa-trash-o fa-lg btn btn-danger btn-s delete", data: {confirm: "Are you sure?"} %>
          <% end %>

            <%= link_to "Edit", edit_location_item_path(@location, @item), method: "get", remote: true, class: "btn btn-primary btn-s edit-show" %>

          <% if @item.records.count > 0 %>
            <%= link_to "History", location_item_records_path(@location, @item), class: "btn btn-primary btn-s" %>
          <% end %>
          
          <% if @item.is_borrowed %>
            <%= link_to "Item returned to lender?", location_item_path(@location, @item), method: :delete, class: "btn btn-danger btn-s" %>
          <% else %>
            <% if @item.is_out? %>
              <%= link_to "Received from borrower?", return_item_path(@item.id), method: "post", remote: true, class: "btn btn-primary btn-s", id: "return-button" %>
            <% else %>
              <%= link_to "Lend out this item", '#', class: "btn btn-primary btn-s lend-button" %>
            <% end %>
          <% end %>

        </p>
      <% end %>
      
      <div class="crud">
        <% if @edit %>
          <%= render partial: "edit", locals: {using_modal: true} %>
        <% elsif @lend %>
          <%= render partial: "is_out_form" %>
        <% end %>
      </div>
    </div>

app/views/items/index.html.erb
<h1><%= link_to @location.name.upcase, edit_location_path(@location) %> Items</h1>

<div class="field">
  <%= form_tag(location_item_search_path(@location), method: "get", remote: true) do %>
    
    <%= text_field_tag :q, nil, placeholder: 'Search item name/tags' %>
    <%= submit_tag("Search") %>
  <% end %>

</div>


<div class="search-results">
  <div class="search_container">
    <% if @results %>
      

    <% end %>
  </div>
</div>


<div class="container-fluid">
  
  <div id="masonry_container">
    <div class ="item-block">
      <div class = "add-more">
        <%= link_to '', new_location_item_path(@location,@item), class:"fa fa-plus fa-5x", remote: true %>
      </div>
    </div>
    
    <% @items.each do |item| %>

      <%= render partial: 'item', locals: {item: item} %>

    <%end%>
  </div>
    <div class="items-index-infinite-scrolling">
      <%= paginate @items %>
    </div>
</div>





<div id='modal-div'>
</div>

<div id='show-modal-div'>
</div>

app/views/items/index.js.erb
// var $items = $("<%= j render @items %>");


// // $('#masonry_container').isotope( 'appended', $items );


// 	// var $search = $("<%= j render 'search_results' %>");
// 	// $('.search_container').isotope( 'insert', $search );

// $('#masonry_container').append("<%= j render @items %>");

// <% if @items.last_page? %>
//   $(window).off('scroll');
//   $('.pagination').remove();
// <% else %>
//   $('.pagination').replaceWith('<%= j paginate @items %>');
// <% end %>
// <% sleep 0.8 %>

app/views/items/new.html.erb
<div class = " container ">
  <%= render partial: 'new_form', locals: {using_modal: false} %>
</div>

	

app/views/items/new.js.erb
$('#modal-div').html('<%= j render "modal" %>');
$('#newItem').modal('show');
$(".modal-body").empty().append("<%= j render partial: 'new_form', locals: {using_modal: true} %>");
console.log('this worked');
$('#new_item').validate({
	rules: {
		"item[name]": { required: true },
		"item[description]": { required: true },
		"item[borrowed_from]": { required: true },
		"item[due_date]": { required: true, date: true }
	}
});

$(function() {
	$('#item_is_borrowed').change(function() {
		if($('#item_is_borrowed').prop('checked')) {
			$('.record-form').show();
		}
		else {
			$('.record-form').hide();
		}
	});

	$('.date').datepicker({
		dateFormat: 'yy-mm-dd'
	});

	$("#item_tag_list").tagit();
	
});

app/views/items/search_submit.js.erb
<% if !@results.empty? %>

	console.log("<p>Search results:</br>" +
		"<%= @results.map { |result| result.name }.join('<br/>') %>");
	// $('.search_container').empty().append("<h1>Search results: <%= j params[:q] %></h1><hr>" + "<%= j render 'search_results' %><hr><h1>All Items</h1>");
	$('.search_results').prepend("<h3>Search results: </h3>");
	$('.search_container').empty();
	var $search = $("<%= j render 'search_results' %>");
	$('.search_container').isotope( 'insert', $search );
	// $('#masonry_container').isotope('layout');
	// $('.search_container').isotope('layout');
	// $('.search-results').empty().append("<p>Search results: </br>"); 
	// <% @results.each do |result| %>
	// 	$('.search-results').append(<%= link_to "#{result}", location_item_path(result.location_id, result.id) %>);
	// <% end %>
	// $('.search-results').empty().append("<p>Search results: </br>" + "<%= @results.map { |result| result.name }.join(', ') %>");

<% else %>


	$('.search_container').empty().append("<h1>No results found. Try searching again.</h1><hr>" );		
<% end %>

app/views/items/show.html.erb
<%= render partial: 'show_model', locals: {using_modal: false} %>

app/views/items/show.js.erb
<% if @edit || @lend %>
	console.log('edit');
	$('#show-modal-div').html('<%= j render "show_model" %>');
	$('#showItem').modal('show');

	// someone make this fker below work to run datepicker, tagit, and js form validations
	$('.date').datepicker({
		dateFormat: 'yy-mm-dd'
	});
	$('#item_tag_list').tagit();
	$('#showItem').on('shown.bs.modal', function() {
		console.log('modal ready to serve');
		$('#item_tag_list').tagit();
	});
	$('#showItem').on('show.bs.modal', function() {
		console.log('modal ready to serve');
		$('#item_tag_list').tagit();
	});
	$('.edit_item').validate({
		rules: {
			"item[name]": { required: true },
			"item[description]": { required: true }
		}
	});
<% end %>




$('#show-modal-div').html('<%= j render "show_model" %>');
$('#showItem').modal('show');
console.log('this worked');





function bindLendButton(){
	$('.lend-button').bind("click", function() {

		$(this).replaceWith("<%= j render partial: 'is_out_form' %>");
		$('.date').datepicker({
			dateFormat: 'yy-mm-dd'
		});
		$('#new_record').validate({
			
			rules: {
				"record[borrower_name]": { required: true },
				"record[date_due]": { required: true, date: true }
			}
		});
	});
}

bindLendButton();