config/routes.rb
Rails.application.routes.draw do

  

  get 'records/new'

  devise_for :users, :controllers => { registrations: 'registrations', 
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'tags/:tag', to: 'items#index', as: :tag

  root 'static_pages#home'
  get 'static_pages/about', as: :about
  post 'global_search' => 'static_pages#global_search_results', as: 'global_search'
  post 'return_item/:item_id' => 'items#return_item', as: 'return_item'
  get 'lend_item/:item_id' => 'items#lend_item', as: 'lend_item'

  resources :locations do 
    get 'search'  =>  'items#search_submit', as: 'item_search'
    resources :items do
      resources :records, only: [:new, :create, :index]
    end 
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :user
	has_many :items, dependent: :destroy

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "Logo.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true, length: { maximum: 24 }
  
  paginates_per 60
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_location, only: [:show, :edit, :update, :destroy,]
  before_action :set_user
  before_action :set_item, ounly: [:show]

  def show
  end

  def index
    @locations  = @user.locations.order('name ASC').page(params[:page])
    @user_items = current_user.items.page(params[:items_page])
    @cheked_out = @user_items.all.where(is_out: 'true').page(params[:checked_page])
    overdue   = @cheked_out.select { |item| item.records.last.date_due < Date.today }
    overdue_ids = overdue.map {|i| i.id}
    @overdue = Item.where(id: overdue_ids).page(params[:overdue_page])

    respond_to do |format|
      format.html 
      format.js 
    end
  end

  def new
    @location = Location.new
  end

  def create
      @location = current_user.locations.build(location_params)
      @location.user_id = @user.id
      if @location.save
        flash[:success] = "Location #{@location.name} added."
        redirect_to locations_path
      else
        render 'new'
      end
  end

  def edit
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def update
    if @location.update_attributes(location_params)
      flash[:notice] = "Location #{@location.name} updated."
      redirect_to locations_path #it would redirect to locations_show, instead of locations_path
    else
      render :edit
    end
  end

  def destroy
    @location.destroy
    flash[:alert] = "Location #{@location.name} deleted."
    redirect_to locations_url
  end

  def search_submit
    
    respond_to do |format|
      format.js
    end
  end

  private

    def set_user 
       @user = current_user
    end 

    def set_item
      @item =  current_user.items.find_by(id: params[:id])
    end

    def set_location
     @location = current_user.locations.find_by(id: params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :description, :is_out, :due_date, :tag_list, :avatar, records_attributes: [:date_due, :borrower_name])
    end
    
    def location_params
      params.require(:location).permit(:name, :description, :tag_list, :avatar)
    end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_edit.html.erb
<div class="modal fade" id="editLocation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Location</h4>
      </div>
       <div class="modal-body">
        <%= bootstrap_form_for [@location] do |f| %>
      	  <%= f.file_field :avatar %>
					<%= f.text_field :name %>
          <%= f.submit %>
            <% end %>
      </div>
		</div>
  </div>
</div>
        
         
    
         
        
        

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <%= f.file_field :avatar %>
	<%= f.label :name %>
	<%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/locations/_location.html.erb
<div class ="location-block">
    <div class = "item-avatar img-center">
			<%= link_to (image_tag location.avatar.url(:medium), class: "img img-responsive img-center"), location_items_path(location)%>
		</div>
    <h4><%= link_to location.name, location_items_path(location) %></h4>
    <div class = "location-info">
    		<%= link_to "Edit location", edit_location_path(location) ,class: "btn btn-warning", remote: true %>
    		<%= link_to "New item", new_location_item_path(location),class: "btn btn-info", remote: true %>
    </div>

</div>

app/views/locations/_modal.html.erb
<div class="modal fade" id="newItem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Location</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form", locals: {using_modal: true} %>
      </div>
    </div>
  </div>
</div>

app/views/locations/edit.html.erb
<div class = "container">
<%= form_for(@location, method: :patch) do |f| %>
<%= f.file_field :avatar %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>

	<%= f.submit %>
<% end %>
</div>

app/views/locations/edit.js.erb
$('#edit-modal-div').html('<%= j render partial: "edit" %>');
$('#editLocation').modal('show');
console.log('this edit worked');

app/views/locations/index.html.erb
<%= render('layouts/navbar') %>
<div class="flash_messages"><%= flash_messages %> </div>
<div role="tabpanel">

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="locations">
      <h1 class = "greeting">Hi <%=link_to current_user.username,edit_user_registration_path %></h1>
      <div class="container-fluid">
        <div class="row image-tiles">
          <% if current_user.locations %>
          <% else %>
              <h1>Lets get started</h1>
              <p> click the blue + sign to create a location</p>
          <% end %>

          <div class="search-results">
            <% if @results %>
                <%= @results %>
            <% end %>
          </div>

          <div id="loc_masonry_container">
            <div class="location-block">
              
                <%= link_to '', new_location_path, class:"fa fa-plus fa-5x", remote: true %>

            </div>

              <% @locations.each do |location| %>
                <%= render partial: 'location', locals: {location: location} %>
              <% end %>

          </div>
            <div class="infinite-scrolling">
              <%= paginate @locations, params: { anchor: "locations" } %>
            </div>
        </div>
        

      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="items">
      <h1>All Items</h1>

        <div id="user_items">
          <% @user_items.each do |item| %>
             <%= render partial: 'items/item', locals: {item: item }%>

          <%end%>
        </div>

      <div class="user-items-infinite-scrolling">
        <%= paginate @user_items, param_name: "items_page", params: { anchor: "items"} %>
      </div>
    </div>


    <div role="tabpanel" class="tab-pane" id="messages">
      <h1>Out Items</h1>
      <div class="container-fluid ">
        <div id="checked_out_items">
          <% @cheked_out.each do |item| %>
          <%= render partial: 'items/item', locals: {item: item} %>

          <%end%>
        </div>
      </div>
      <div class="checked-out-infinite-scrolling">
        <%= paginate @cheked_out, param_name: "checked_page", params: { anchor: "messages"} %>
      </div>
    </div>

    <div role="tabpanel" class="tab-pane" id="settings">
      <h1>Overdue Items</h1>
      <div class="container-fluid ">
        <div id="overdue_items">
          <% @overdue.each do |item| %>
            <%= render partial: 'items/item', locals: {item: item} %>
          <% end %>
        </div>
        <div class="overdue-infinite-scrolling">
          <%= paginate @overdue, param_name: "overdue_page", params: { anchor: "settings"} %>
        </div>
      </div>
    </div>


  </div>
</div>




<div id='show-modal-div'>
</div>

<div id='modal-div'>
</div>

<div id='edit-modal-div'>
</div>

app/views/locations/index.js.erb
// $('.masonry_container').append('<%= j render @locations %>');
// <% if @locations.last_page? %>
//   $(window).off('scroll');
//   $('.pagination').remove();
// <% else %>
//   $('.pagination').replaceWith('<%= j paginate @locations %>');
// <% end %>
// <% sleep 0.8 %>

app/views/locations/new.html.erb
<div class = "container">

<%= render 'form' %>

</div>

app/views/locations/search_submit.js.erb
console.log("SEARCH");
var $masonry_container = $('#masonry_container').imagesLoaded( function() {
// init
$masonry_container.isotope({
  // options
  itemSelector: '.item-block',
  masonry: {
    columnWidth: 25,
    gutter: 10,
    isFitWidth: true
  },

  layoutMode: 'masonry',
  $masonry_container.isotope('layout');
});

app/views/locations/show.html.erb
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.erb</p>
<% if @location %>
<%= @location.name %>
<%= @location.description %>
    <% end %>


<p><%= link_to 'Back', locations_path %></p>