config/routes.rb
Rails.application.routes.draw do

  

  get 'records/new'

  devise_for :users, :controllers => { registrations: 'registrations', 
                                      omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'tags/:tag', to: 'items#index', as: :tag

  root 'static_pages#home'
  get 'static_pages/about', as: :about
  post 'global_search' => 'static_pages#global_search_results', as: 'global_search'
  post 'return_item/:item_id' => 'items#return_item', as: 'return_item'
  get 'lend_item/:item_id' => 'items#lend_item', as: 'lend_item'

  resources :locations do 
    get 'search'  =>  'items#search_submit', as: 'item_search'
    resources :items do
      resources :records, only: [:new, :create, :index]
    end 
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted"><%= link_to 'Home', root_path %></p>
    
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-center">
      <div class = "nav-logo">
        <%= link_to((image_tag "Logo-2.png", size: "150x75"), root_path) %>

      </div>
    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         
            
          

          <li>
            <%= form_tag(global_search_path) do %>
              <%= text_field_tag :q, nil, placeholder: 'Search item name' %>
              <%= submit_tag("Search") %>
            <% end %>
          </li>

            <!-- Single button -->
          <li>
            <div class=" new">
              <button  class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                New <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <% current_user.locations.each do |location|%>
                  <%if location.id%>
                  <li><%= link_to ("Item at  #{location.name}"), new_location_item_path(location), remote: true %></li>
                  <% end %>
                <%end%>
                <li class="divider"></li>
                <li> <%= link_to 'Location', new_location_path, class: 'btn btn-primary', remote: true %></li>
              </ul>
            </div>
          </li>
          <!-- end dropdown button -->
          
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn-inverse navbar-right" %></li> 
        
         
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path, data: {toggle: "modal", target: "#signIn"}, id: "sign-in-button", remote: true %></li>

          <li><%= link_to 'Join', new_user_registration_path, data: {toggle: "modal", target: "#signUp"}, remote: true %></li>
        <% end %>  
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_navbar.html.erb
  <!-- Nav tabs -->
  <ul class="nav nav-tabs nav-justified jquerytabs" role="tablist">
    <li role="presentation" class="active"><a href="#locations" aria-controls="home" role="tab" data-toggle="tab">Locations</a></li>
    <li role="presentation"><a href="#items" aria-controls="profile" role="tab" data-toggle="tab">All Items</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Out Items</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Overdue Items</a></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IhAVE</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Fixed navbar -->
   <%= render('layouts/header') %>


    <!-- Begin page content -->
    <div id="main-wrapper">

      <%= yield %>
          
    </div>

    
    <%= javascript_include_tag 'application' %>
</body>
</html>